### ISSUE TITLE
Puesta en marcha del proyecto

### ISSUE THREAD

**Issue by RFloresDev** [Alexgv0/EntregaFinal-BackEnd2-CoderHouse#1]
Saludos Alex, Espero estés bien.

**Comment by Alexgv0** [comment]
Muchas gracias, y disculpa la demora, envié el .env por la plataforma pero por las dudas le paso los 3 por acá.

________________________________
De: Richard Flores ***@***.***>
Enviado: jueves, 5 de diciembre de 2024 23:43
Para: Alexgv0/EntregaFinal-BackEnd2-CoderHouse ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: [Alexgv0/EntregaFinal-BackEnd2-CoderHouse] Puesta en marcha del proyecto (Issue #1)


Saludos Alex, Espero estés bien.

Podrías compartirme las variables de entorno (la estructura) para hacer andar el proyecto por favor, tu código es muy limpio y está bien escrito, me ha servido mucho como guía. ***@***.******@***.***>

De antemano Gracias

**Comment by RFloresDev** [comment]
Ojo yo no soy profe ni nada, solo soy un aprendiz de desarrollador que estoy aprendiendo, pero no me llegó ninguno de los archivos

**Comment by Alexgv0** [comment]
Disculpa, fue mi error que no me había dado cuenta porque respondí por el correo, ahora envio los .env por acá
[.env.zip](https://github.com/user-attachments/files/18048973/default.env.zip)

**Comment by RFloresDev** [comment]
Muchas gracias Alex, eres un crack

**Comment by Alexgv0** [comment]
Muchas gracias a ti, la verdad ni sabía por donde me estabas escribiendo, estaba viendo los mensajes en el correo jaja
